theme: jekyll-theme-minimal
name: Leonardo Ortiz
markdown: redcarpet 
highlighter: pygments 
redcarpet: extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
